"""Domain entities, value objects, and enums for Phase 4 LLM Answer Orchestration."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from financial_rag.domain.entities.reasoning import (
    CalculationResult,
    Citation,
    Claim,
    FinancialFact,
    GroundingStatus,
    ReasoningPlan,
)
from financial_rag.domain.entities.retrieval import RetrievalFilter


def utc_now() -> datetime:
    return datetime.now(UTC)


class ResponseStyle(StrEnum):
    """Presentation style for synthesized answers."""

    CONCISE = "concise"
    STANDARD = "standard"
    DETAILED = "detailed"
    ANALYTICAL = "analytical"


class AnswerStatus(StrEnum):
    """Overall terminal status of answer generation."""

    COMPLETED = "completed"
    PARTIALLY_ANSWERED = "partially_answered"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    CONFLICTING_EVIDENCE = "conflicting_evidence"
    GROUNDING_FAILED = "grounding_failed"
    CALCULATION_FAILED = "calculation_failed"
    GENERATION_FAILED = "generation_failed"
    INVALID_QUERY = "invalid_query"


class AnswerStreamEventType(StrEnum):
    """Event types for SSE streaming answer synthesis."""

    STAGE_START = "stage_start"
    REASONING_COMPLETE = "reasoning_complete"
    TOKEN_DELTA = "token_delta"
    CALCULATIONS = "calculations"
    CITATIONS = "citations"
    VALIDATION_RESULT = "validation_result"
    ANSWER_COMPLETE = "answer_complete"
    ERROR = "error"


@dataclass
class AnswerStreamEvent:
    """A typed event emitted during streaming answer synthesis."""

    sequence: int
    event_type: AnswerStreamEventType
    payload: dict[str, Any]
    timestamp: datetime = field(default_factory=utc_now)


@dataclass
class AnswerRequest:
    """Domain model representing an incoming inquiry for answer generation."""

    query: str
    tenant_id: str = "default_tenant"
    user_id: str | None = None
    response_style: ResponseStyle = ResponseStyle.STANDARD
    detail_level: str = "standard"
    include_citations: bool = True
    citation_style: str = "bracketed"  # e.g., "[C1]"
    filters: RetrievalFilter | None = None
    top_k: int = 10
    use_reranker: bool = True
    custom_instructions: str | None = None


@dataclass
class LLMAnswerSection:
    """A distinct structural section within an LLM-generated answer."""

    heading: str
    content: str
    claim_ids: list[str] = field(default_factory=list)
    citation_markers: list[str] = field(default_factory=list)


@dataclass
class LLMAnswerOutput:
    """Structured response schema generated by the LLM."""

    summary: str
    detailed_answer: str
    sections: list[LLMAnswerSection] = field(default_factory=list)
    calculation_explanation: str | None = None
    cited_claim_ids: list[str] = field(default_factory=list)
    citation_markers: list[str] = field(default_factory=list)
    limitations_disclosed: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class ValidationFailure:
    """Record of a single validation failure in the 8-stage answer validator."""

    stage: str
    code: str
    message: str
    severity: str  # "fatal", "retryable", "warning"
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class ValidationResult:
    """Comprehensive outcome of the 8-stage answer validation audit."""

    valid: bool
    failures: list[ValidationFailure] = field(default_factory=list)
    numerical_discrepancies: list[str] = field(default_factory=list)
    invalid_citations: list[str] = field(default_factory=list)
    unsupported_claims: list[str] = field(default_factory=list)
    retry_recommended: bool = False

    @property
    def has_fatal_failures(self) -> bool:
        return any(f.severity == "fatal" for f in self.failures)


@dataclass
class AnswerResponse:
    """Authoritative, audited, and formatted answer response container."""

    answer_id: UUID = field(default_factory=uuid4)
    query_id: UUID = field(default_factory=uuid4)
    tenant_id: str = "default_tenant"
    user_id: str | None = None
    status: AnswerStatus = AnswerStatus.COMPLETED
    answer_text: str = ""
    claims: list[Claim] = field(default_factory=list)
    citations: list[Citation] = field(default_factory=list)
    calculations: list[CalculationResult] = field(default_factory=list)
    facts: list[FinancialFact] = field(default_factory=list)
    reasoning_plan: ReasoningPlan | None = None
    grounding_status: GroundingStatus = GroundingStatus.GROUNDED
    confidence_score: float = 1.0
    warnings: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    execution_time_ms: dict[str, float] = field(default_factory=dict)
    created_at: datetime = field(default_factory=utc_now)
